version: 2.0

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
          - v3-deps-
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: upload coverage report
        command: |
          if [[ "$UPLOAD_COVERAGE" != 0 ]]; then
              bash <(curl -s https://codecov.io/bash)
          fi
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6.1
        environment:
          - TOXENV=checkqa
          - UPLOAD_COVERAGE=0
  py36dj22:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj22
  py36dj30:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj30
  py36djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-djmaster
  py37dj22:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj22
  py37dj30:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj30
  py37djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-djmaster
  py38dj22:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj22
  py38dj30:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj30
  py38djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-djmaster

workflows:
  version: 2
  test:
    jobs:
      - lint
      - py36dj22
      - py36dj30
      - py36djmaster
      - py37dj22
      - py37dj30
      - py37djmaster
      - py38dj22
      - py38dj30
      - py38djmaster
