# Generated by Django 2.1.4 on 2019-01-22 06:00

from django.db import migrations, models
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [("zengo", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="zendeskuser",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="zendeskuser",
            name="role",
            field=konst.models.fields.ConstantChoiceCharField(
                choices=[
                    ("end-user", "end_user"),
                    ("agent", "agent"),
                    ("admin", "admin"),
                ],
                default="end-user",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
