# Generated by Django 2.1.4 on 2019-01-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zengo", "0003_auto_20181212_2312")]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="event", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="ticket", old_name="created", new_name="created_at"
        ),
        migrations.RenameField(
            model_name="zendeskuser", old_name="created", new_name="created_at"
        ),
    ]
