# Generated by Django 2.1.4 on 2019-02-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zengo", "0003_zendeskuser_photos_json")]

    operations = [migrations.RemoveField(model_name="ticket", name="description")]
