# Generated by Django 2.1.4 on 2019-01-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zengo", "0004_auto_20190102_0305")]

    operations = [
        migrations.RenameField(
            model_name="ticket", old_name="updated", new_name="updated_at"
        )
    ]
