# Generated by Django 2.2.10 on 2020-03-10 17:33

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zengo', '0005_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=konst.models.fields.ConstantChoiceCharField(blank=True, choices=[('urgent', 'urgent'), ('high', 'high'), ('normal', 'normal'), ('low', 'low')], max_length=8),
        ),
    ]
