# Generated by Django 3.2.13 on 2022-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zengo", "0006_auto_20200310_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="remote_ticket_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
