# Generated by Django 2.1.4 on 2019-01-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zengo", "0006_auto_20190105_0732")]

    operations = [
        migrations.RemoveField(model_name="event", name="actor"),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
