# Generated by Django 2.1.4 on 2019-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zengo", "0007_auto_20190114_0620")]

    operations = [
        migrations.RemoveField(model_name="event", name="json"),
        migrations.AlterField(
            model_name="event", name="raw_data", field=models.TextField(max_length=1024)
        ),
    ]
