# Generated by Django 2.1.4 on 2019-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zengo", "0008_auto_20190114_0832")]

    operations = [
        migrations.RemoveField(model_name="event", name="processed"),
        migrations.AddField(
            model_name="event",
            name="remote_ticket_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
