# Generated by Django 2.1.4 on 2019-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zengo", "0009_auto_20190114_0840")]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="custom_fields",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
